FROM debian:buster

RUN apt-get update -y && apt-get upgrade -y && \
	apt-get install -y mariadb-server

COPY ./tools/init.sh ./
COPY ./conf/50-server.cnf //etc/mysql/mariadb.conf.d/50-server.cnf

EXPOSE 3306

RUN chmod 777 ./setup.sh

CMD ["sh", "-c", "./setup.sh"]
