# 도커 컴포즈를 사용하는 이유?
# 간단하게 누군가가 잘 만들어 준 이미지들을 조합해서 서버를 간단하게 구축할 수 있다
# 설정까지 이미지에서 다 할 수 있다

# pid 1은 모든 프로세스의 부모 프로세스, 가장 첫번째로 실행되는 프로세스
# 따라서 pid 1d을 종료하면 하위에 있는 모든 프로세스가 같이 종료된다는 뜻
# 만약 어떤 프로세스가 pid 1 하위 프로세스로 들어가있지 않으면, 마지막에 pid 1 프로세스가 종료되어도 좀비 프로세스로 남는다

services:
  # 서비스의 이름
  nginx:
    build: ./
  wordpress:
  mariadb:
